apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: guestbook
  name: guestbook-route
  namespace: guestbook
spec:
  subdomain: guestbook
  port:
    targetPort: 80
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: guestbook-ui
    weight: 100
